package apidiscovery

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/Prideth/terraform-provider-sap-integration-suite/internal/apimeta"
	"github.com/Prideth/terraform-provider-sap-integration-suite/internal/features"
)

// ReportPath is where the generated discovery report lives.
const ReportPath = "docs/api-discovery-report.md"

// WriteReport renders the discovery report from the committed snapshots and
// writes it to path.
func WriteReport(path string) error {
	return os.WriteFile(path, []byte(RenderReport()), 0o600)
}

// RenderReport renders the discovery report: per service, what its contract
// holds, what the provider uses, what could back a resource, and what is
// excluded and why. It depends only on the snapshots, the client contracts,
// the classification and the feature catalog, so its output is deterministic
// and the report test can require the committed file to match it.
func RenderReport() string {
	var b strings.Builder
	b.WriteString(`# API discovery report

<!-- Generated by "go run ./cmd/apidiscovery -offline -report docs/api-discovery-report.md" (make api-discovery-report).
     Do not edit by hand; change the snapshots, client contracts or classification instead. -->

This report lists every service root the provider knows, and for each one
with a committed contract snapshot in ` + "`testdata/api-metadata`" + `, every
entity set and operation with what the provider makes of it:

- **used**: a client contract of the provider reads, writes or calls it
  (derived from the ` + "`Contract`" + ` of each client package);
- **candidate**: it could back a resource or data source, and the named
  catalog entry tracks it;
- **excluded**: it is deliberately not modelled, with the reason.

A snapshot proves that an entity exists and what it looks like. It does not
prove that SAP supports writing it: every mutable resource additionally needs
SAP documentation, official SAP tooling, or a safe verification on a tenant
(see CONTRIBUTING.md, "API discovery").

`)
	b.WriteString("## Services\n\n| Service | Protocol | Snapshot | Entity sets | Operations | Used | Candidates | Excluded |\n|---|---|---|---:|---:|---:|---:|---:|\n")
	type loaded struct {
		svc  Service
		snap *apimeta.Service
		rows []Row
	}
	var all []loaded
	for _, svc := range Services {
		snap, err := apimeta.LoadSnapshot(svc.ID)
		if err != nil {
			fmt.Fprintf(&b, "| [%s](#%s) | %s | none yet | | | | | |\n", svc.ID, svc.ID, protocolLabel(svc.Protocol))
			all = append(all, loaded{svc: svc})
			continue
		}
		rows := Classify(snap)
		counts := countStatus(rows)
		fmt.Fprintf(&b, "| [%s](#%s) | %s | %s | %d | %d | %d | %d | %d |\n", svc.ID, svc.ID, protocolLabel(svc.Protocol),
			snap.CapturedAt, len(snap.EntitySets)+len(snap.Singletons), countKind(rows, "operation"),
			counts[StatusUsed], counts[StatusCandidate], counts[StatusExcluded])
		all = append(all, loaded{svc: svc, snap: snap, rows: rows})
	}
	b.WriteString("\n")

	for _, l := range all {
		renderService(&b, l.svc, l.snap, l.rows)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderService(b *strings.Builder, svc Service, snap *apimeta.Service, rows []Row) {
	fmt.Fprintf(b, "## %s\n\n%s.\n\n", svc.ID, svc.Title)
	fmt.Fprintf(b, "- Protocol: %s\n- Evidence for the service root: %s\n", protocolLabel(svc.Protocol), svc.Evidence)
	fmt.Fprintf(b, "- Acceptance suites: %s\n", gateList(svc.Capabilities))
	fmt.Fprintf(b, "- Configuration: %s\n", codeList(svc.Env))
	if snap == nil {
		b.WriteString("- Snapshot: none yet. Fetch one with `go run ./cmd/apidiscovery -services " + svc.ID +
			" -update` once the service is configured, then classify its entity sets.\n\n")
		return
	}
	fmt.Fprintf(b, "- Snapshot: `testdata/api-metadata/%s.json`, captured %s from %s\n", svc.ID, snap.CapturedAt, snap.Source)
	reach, unreach, unresolved := 0, 0, 0
	if snap.Graph != nil {
		reach, unreach, unresolved = len(snap.Graph.Reachable), len(snap.Graph.Unreachable), len(snap.Graph.Unresolved)
	}
	fmt.Fprintf(b, "- Contract: %d entity sets, %d singletons, %d entity types, %d complex types, %d enum types, %d operations; "+
		"%d types reachable from the entity sets and operations, %d unreachable, %d unresolved references\n\n",
		len(snap.EntitySets), len(snap.Singletons), len(snap.EntityTypes), len(snap.ComplexTypes), len(snap.EnumTypes),
		len(snap.Operations), reach, unreach, unresolved)

	byStatus := map[Status][]Row{}
	for _, r := range rows {
		byStatus[r.Status] = append(byStatus[r.Status], r)
	}

	if used := byStatus[StatusUsed]; len(used) > 0 {
		fmt.Fprintf(b, "### Used by the provider (%d)\n\n| Name | Kind | Type or method | Client packages |\n|---|---|---|---|\n", len(used))
		for _, r := range used {
			fmt.Fprintf(b, "| %s | %s | %s | %s |\n", r.Name, r.Kind, shortType(r.Type), codeList(r.Packages))
		}
		b.WriteString("\n")
	}
	if cands := byStatus[StatusCandidate]; len(cands) > 0 {
		fmt.Fprintf(b, "### Candidates (%d)\n\n| Name | Kind | Catalog entry | Catalog status | Note |\n|---|---|---|---|---|\n", len(cands))
		sort.SliceStable(cands, func(i, j int) bool { return cands[i].Feature < cands[j].Feature })
		for _, r := range cands {
			fmt.Fprintf(b, "| %s | %s | `%s` | %s | %s |\n", r.Name, r.Kind, r.Feature, catalogStatus(r.Feature), cell(r.Reason))
		}
		b.WriteString("\n")
	}
	if excl := byStatus[StatusExcluded]; len(excl) > 0 {
		fmt.Fprintf(b, "### Excluded (%d)\n\n", len(excl))
		renderExcluded(b, excl)
	}
	if un := byStatus[StatusUnclassified]; len(un) > 0 {
		fmt.Fprintf(b, "### Not classified yet (%d)\n\n", len(un))
		for _, r := range un {
			fmt.Fprintf(b, "- %s %s\n", r.Kind, r.Name)
		}
		b.WriteString("\n")
	}
	if snap.Graph != nil && len(snap.Graph.Unreachable) > 0 {
		fmt.Fprintf(b, "### Types not reachable from any entity set or operation (%d)\n\n", len(snap.Graph.Unreachable))
		for _, t := range snap.Graph.Unreachable {
			fmt.Fprintf(b, "- %s\n", t)
		}
		b.WriteString("\n")
	}
}

// renderExcluded groups exclusions by reason, so that forty message
// monitoring sets read as one decision.
func renderExcluded(b *strings.Builder, rows []Row) {
	type group struct {
		reason, feature string
		names           []string
	}
	var groups []*group
	index := map[string]*group{}
	for _, r := range rows {
		key := r.Reason + "\x00" + r.Feature
		g, ok := index[key]
		if !ok {
			g = &group{reason: r.Reason, feature: r.Feature}
			index[key] = g
			groups = append(groups, g)
		}
		g.names = append(g.names, r.Name)
	}
	b.WriteString("| Names | Reason | Catalog entry |\n|---|---|---|\n")
	for _, g := range groups {
		feature := ""
		if g.feature != "" {
			feature = "`" + g.feature + "`"
		}
		fmt.Fprintf(b, "| %s | %s | %s |\n", strings.Join(g.names, ", "), cell(g.reason), feature)
	}
	b.WriteString("\n")
}

func countStatus(rows []Row) map[Status]int {
	out := map[Status]int{}
	for _, r := range rows {
		out[r.Status]++
	}
	return out
}

func countKind(rows []Row, kind string) int {
	n := 0
	for _, r := range rows {
		if r.Kind == kind {
			n++
		}
	}
	return n
}

func catalogStatus(key string) string {
	f, ok := features.Lookup(key)
	if !ok {
		return "not in catalog"
	}
	return string(f.SupportStatus)
}

func protocolLabel(p string) string {
	switch p {
	case apimeta.ProtocolODataV2:
		return "OData V2"
	case apimeta.ProtocolODataV4:
		return "OData V4"
	case apimeta.ProtocolOpenAPI:
		return "OpenAPI"
	}
	return p
}

func gateList(caps []string) string {
	out := make([]string, len(caps))
	for i, c := range caps {
		out[i] = "`SAP_INTEGRATION_SUITE_ACC_" + c + "`"
	}
	return strings.Join(out, ", ")
}

func codeList(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}

// shortType drops the namespace of an entity type.
func shortType(t string) string {
	if i := strings.LastIndex(t, "."); i >= 0 && !strings.HasPrefix(t, "Edm.") {
		return t[i+1:]
	}
	return t
}

func cell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
